# Generated by Django 4.2.4 on 2023-08-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_history_unique_matchup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="playing",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
